<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Remove="TUnit" />

    <Using Remove="TUnit.Core" />
    <Using Remove="TUnit.Assertions" />
    <Using Remove="TUnit.Assertions.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Web\Results.AspNetCore\LightningArc.Results.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\Web\CORS.AspNetCore\LightningArc.CORS.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\Web\OpenAPI.AspNetCore\LightningArc.OpenAPI.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\Core\Json\LightningArc.Json.csproj" />
    <ProjectReference Include="..\..\..\src\Core\Core\LightningArc.Core.csproj" />
  </ItemGroup>
</Project>
