<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <!-- Test Project Identification -->
    <IsPackable>false</IsPackable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IsTestProject>true</IsTestProject>
    
    <!-- Build -->
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --config-file "$(MSBuildThisFileDirectory)testconfig.json"</TestingPlatformCommandLineArguments>
    
    <!-- Speed: Only build in Test configuration -->
    <Configurations>Debug;Release;LamaDebug;Dev</Configurations>
  </PropertyGroup>

  <Target Name="SkipTestBuild" BeforeTargets="BeforeBuild" Condition="'$(Configuration)' == 'Dev'">
    <Message Importance="high" Text="Skipping test project build because configuration is 'Dev'." />
    <PropertyGroup>
      <IsSkipBuild>true</IsSkipBuild>
    </PropertyGroup>
  </Target>

  <!-- Prevent compilation and other main tasks in Dev config -->
  <PropertyGroup Condition="'$(Configuration)' == 'Dev'">
    <CoreBuildDependsOn></CoreBuildDependsOn>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="TUnit.Core" />
    <Using Include="TUnit.Assertions" />
    <Using Include="TUnit.Assertions.Extensions" />
  </ItemGroup>
</Project>