<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;net9.0;net10.0</TargetFrameworks>

	<RootNamespace>LightningArc.Primitives</RootNamespace>

	<NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
	<AssemblyName>LightningArc.Primitives</AssemblyName>
	<PackageTags>lightningarc dotnet clean-code value-objects domain-driven-design validation email cpf cnpj</PackageTags>
	<Description>A collection of immutable Value Objects (Email, Cpf, Cnpj, etc.) with built-in validation for Domain-Driven Design.</Description>
  </PropertyGroup>

  <ItemGroup>
	<InternalsVisibleTo Include="LightningArc.Primitives.Results" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="PolySharp" PrivateAssets="All" />
  </ItemGroup>
</Project>



