<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;net9.0;net10.0</TargetFrameworks>

	<RootNamespace>LightningArc.Data.EntityFramework</RootNamespace>

	<NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>LightningArc.Data.EntityFramework</AssemblyName>
    <PackageTags>lightningarc dotnet clean-code repository-pattern entity-framework efcore</PackageTags>
    <Description>Entity Framework Core implementation of LightningArc repository abstractions.</Description>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="PolySharp" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Abstractions\LightningArc.Data.Abstractions.csproj" />
  </ItemGroup>

</Project>




