<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;net9.0;net10.0</TargetFrameworks>

	<RootNamespace>LightningArc.Data.ADO</RootNamespace>

	<NoWarn>$(NoWarn);IDE0130</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyName>LightningArc.Data.ADO</AssemblyName>
    <PackageTags>lightningarc dotnet clean-code repository-pattern dapper ado-net</PackageTags>
    <Description>Base repository implementation and helpers for ADO.NET and Dapper integration.</Description>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
	<PackageReference Include="PolySharp" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Data.Abstractions\LightningArc.Data.Abstractions.csproj" />
  </ItemGroup>

</Project>





