<Project>
  <PropertyGroup>
    <!-- Disable all build actions -->
    <TargetFramework>netstandard2.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    
    <!-- Speed: Skip compilation and standard tasks -->
    <Configurations>Debug;Release;LamaDebug;Test</Configurations>
    <SkipBuild>true</SkipBuild>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <CopyBuildOutputToPublishDirectory>false</CopyBuildOutputToPublishDirectory>
    <NoWarn>$(NoWarn);CS2008</NoWarn> <!-- Ignore 'no source files' warning -->
  </PropertyGroup>

  <Target Name="Build" />
  <Target Name="Clean" />
  <Target Name="Rebuild" />
  <Target Name="Publish" />
</Project>