<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFrameworks>netstandard2.0;net9.0;net10.0</TargetFrameworks>
	<OutputType>Library</OutputType>

	<RootNamespace>LightningArc.Metalama.Results</RootNamespace>
	<NoWarn>IDE0130;NU5128;CA1865</NoWarn>

	<MetalamaRemoveCompileTimeOnlyCode>false</MetalamaRemoveCompileTimeOnlyCode>
  </PropertyGroup>

  <PropertyGroup>
	<AssemblyName>LightningArc.Metalama.Results</AssemblyName>
	<PackageTags>lightningarc dotnet clean-code metalama aop aspects result-pattern</PackageTags>
	<Description>Result-pattern specific aspects and utilities using Metalama.</Description>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Metalama.Framework" />
		<PackageReference Include="Metalama.Framework.Sdk" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Metalama\LightningArc.Metalama.csproj" />
		<ProjectReference Include="..\..\Core\Results\LightningArc.Results.csproj" />
   </ItemGroup>
</Project>




